export const TAB_DATA_LIST = [
  { id: 1, title: '멋진 수영장', src: '/images/Header/pool.jpeg' },
  { id: 2, title: '방', src: '/images/Header/room.jpeg' },
  { id: 3, title: '해변 바로 앞', src: '/images/Header/beach.jpeg' },
  { id: 4, title: '컨테이너하우스', src: '/images/Header/container.jpeg' },
  { id: 5, title: '국립공원', src: '/images/Header/park.jpeg' },
  { id: 6, title: '최고의 전망', src: '/images/Header/view.jpeg' },
  { id: 7, title: '한적한 시골', src: '/images/Header/country.jpeg' },
  { id: 8, title: '한옥', src: '/images/Header/korean.jpeg' },
  { id: 9, title: '인기 급상승', src: '/images/Header/hot.jpeg' },
  { id: 10, title: '캠핑장', src: '/images/Header/camping.jpeg' },
  { id: 11, title: '농장', src: '/images/Header/farm.jpeg' },
  { id: 12, title: '기상천외한 숙소', src: '/images/Header/special.jpeg' },
  { id: 13, title: '초소형 주택', src: '/images/Header/small.jpeg' },
  { id: 14, title: '통나무집', src: '/images/Header/log.jpeg' },
  { id: 15, title: '료칸', src: '/images/Header/japanese.jpeg' },
  { id: 16, title: '호숫가', src: '/images/Header/lakeside.jpeg' },
  { id: 17, title: '디자인', src: '/images/Header/design.jpeg' },
  { id: 18, title: '키즈', src: '/images/Header/kids.jpeg' },
  { id: 19, title: '열대지역', src: '/images/Header/tropical.jpeg' },
  { id: 20, title: '스키', src: '/images/Header/skii.jpeg' },
  { id: 21, title: '캐슬', src: '/images/Header/castle.jpeg' },
  { id: 23, title: '신규', src: '/images/Header/new.jpeg' },
  { id: 24, title: 'B&B', src: '/images/Header/bb.jpeg' },
  { id: 25, title: '보트', src: '/images/Header/boat.jpeg' },
  { id: 26, title: '캠핑카', src: '/images/Header/campingcar.jpeg' },
  { id: 27, title: '동굴', src: '/images/Header/cave.jpeg' },
  { id: 28, title: '창작 공간', src: '/images/Header/creative.jpeg' },
  { id: 29, title: '사막', src: '/images/Header/desert.jpeg' },
  { id: 30, title: '돔형주택', src: '/images/Header/dome.jpeg' },
  { id: 31, title: '골프', src: '/images/Header/golf.jpeg' },
  { id: 32, title: '헛간', src: '/images/Header/hut.jpeg' },
  { id: 33, title: '섬', src: '/images/Header/island.jpeg' },
  { id: 34, title: '전문가급 주방', src: '/images/Header/kitchen.jpeg' },
  { id: 35, title: '북극', src: '/images/Header/northpole.jpeg' },
  { id: 36, title: '세상의 꼭대기', src: '/images/Header/peak.jpeg' },
  { id: 37, title: '서핑', src: '/images/Header/surfing.jpeg' },
  { id: 38, title: '상징적 도시', src: '/images/Header/symbol.jpeg' },
  { id: 39, title: '와인농장', src: '/images/Header/wine.jpeg' },
  { id: 40, title: '트리하우스', src: '/images/Header/treehouse.jpeg' },
  { id: 41, title: '타워', src: '/images/Header/tower.jpeg' },
];
